apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-api-config
  namespace: banking
data:
  DATABASE_URL: "postgresql://banking_user:local-dev-password@postgresql-service.banking.svc.cluster.local:5432/banking"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://localstack-service.banking.svc.cluster.local:4566"  # Point to localstack service
  WITHDRAWAL_TOPIC_ARN: "arn:aws:sns:us-east-1:000000000000:withdrawal-events"  # LocalStack format
  LOG_LEVEL: "DEBUG"
  AWS_ACCESS_KEY_ID: "test"  # LocalStack dummy credentials
  AWS_SECRET_ACCESS_KEY: "test"