apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-api
  namespace: banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-api
  template:
    metadata:
      labels:
        app: banking-api
    spec:
      containers:
      - name: banking-api
        image: banking-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: banking-api-config
              key: DATABASE_URL
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: banking-api-config
              key: AWS_REGION
        - name: AWS_ENDPOINT_URL
          valueFrom:
            configMapKeyRef:
              name: banking-api-config
              key: AWS_ENDPOINT_URL
        - name: WITHDRAWAL_TOPIC_ARN
          valueFrom:
            configMapKeyRef:
              name: banking-api-config
              key: WITHDRAWAL_TOPIC_ARN
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: banking-api-config
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: banking-api-config
              key: AWS_SECRET_ACCESS_KEY
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: banking-api-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"